### ISSUE TITLE
{#design-join}: `transform` referenced instead of `transform` in the description of `transfer_when_all`

### ISSUE THREAD

**Issue by katzdm** [brycelelbach/wg21_p2300_std_execution#123]
Section 4.9 describes the behavior of `transfer_when_all`, and contains the following:

> You can think of it as a composition of `transform(when_all(inputs...), scheduler)`, but one that allows for better efficiency through customization.

As far as I can tell, `transform` should instead be `transfer`:

> You can think of it as a composition of `transfer(when_all(inputs...), scheduler)`, but one that allows for better efficiency through customization.

There doesn't appear to be any other reference to a `transform`-identifier in the paper.

**Comment by brycelelbach** [comment]
Thanks.
