### ISSUE TITLE
{#examples-async-inclusive-scan}: Lambda in `async_inclusive_scan` example should capture by reference

### ISSUE THREAD

**Issue by lewissbaker** [brycelelbach/wg21_p2300_std_execution#124]
The lambda passed to `std::for_each` in the `async_inclusive_scan` example currently uses a default capture of `[=]` which causes the `partials` vector to be captured by value and copied rather than just captured by reference.

```c++
       | bulk(tile_count,                                                     // 14
           [=](std::size_t i, std::vector<double>& partials) {                // 14
             auto start = i * tile_size;                                      // 14
             auto end   = std::min(input.size(), (i + 1) * tile_size);        // 14
             std::for_each(output + start, output + end,                      // 14
               [=] (double& e) { e = partials[i] + e; }                       // <---- this line here
             );
           })
```

Just need to change this to a `[&]` default capture instead.
Or alternatively extract the `partials[i]` out into a separate variable.
```
[&](double& e) { e = partials[i] + e; }
```
or
```
[offset=partials[i]](double& e) { e += offset; }
```

**Comment by lewissbaker** [comment]
We could also pass `std::unseq` to the `std::for_each()` call to allow it to be more easily vectorised.

**Comment by mjgarland** [comment]
If we choose to add the `execution::unseq` policy to the `std::for_each`, we might as well add it to the `std::inclusive_scan` calls as well.  Or just leave all of them as sequential algorithms with no policies, of course.

**Comment by brycelelbach** [comment]
Let's not add `unseq`; that adds more complexity to the examples, and it's not essential to the story we're trying to tell with them.
