### ISSUE TITLE
Scheduler query for whether `execute` blocks

### ISSUE THREAD

**Issue by brycelelbach** [brycelelbach/wg21_p2300_std_execution#138]
We need to add a scheduler query for whether `execute` blocks for R1 to retain the capabilities of P0443.

@griwes suggests calling this `this_thread::can_execute_block`, which seems fine as a placeholder.

For discussion and future direction (e.g. queries for whether other things block) see: https://github.com/brycelelbach/wg21_p2300_std_execution/issues/15#issuecomment-871787354.

**Comment by LeeHowes** [comment]
One thought, as I read this issue I read "can_execute_block" as "can this execute a block" rather than "can execute block the caller", even though I was in the meeting yesterday.

**Comment by LeeHowes** [comment]
"std::this_thread::execute_can_block" ? ""::execute_may_block_caller"?

**Comment by brycelelbach** [comment]
> One thought, as I read this issue I read "can_execute_block" as "can this execute a block" rather than "can execute block the caller", even though I was in the meeting yesterday.

Ha, good point. I definitely think there's some ambiguity in the original name suggestion.

I really like having "caller" in the name in some way, to make it clear that it's a query about what happens to the caller (and not some property relating to the forward progress guarantees of any async operations).
