### ISSUE TITLE
tag_invoke poison pill overload is not necessary

### ISSUE THREAD

**Issue by ericniebler** [brycelelbach/wg21_p2300_std_execution#168]
It only exists in libunifex because of a bug in ADL in MSVC.

**Comment by griwes** [comment]
Why is it superfluous? The poison pill is necessary for other CPOs in the standard, isn't it? It was also included in P1895,

**Comment by lewissbaker** [comment]
If I recall correctly, the workaround needed for MSVC was removing the `= delete` on the poison pill and leaving it just as an unimplemented declaration.

**Comment by ericniebler** [comment]
Without the poison pill overload to "seed" the overload set in phase 1, msvc erroneously complains. IIRC, /permissive- fixes the problem. On a conforming compiler, there is no need to seed the overload set in phase 1.

**Comment by ericniebler** [comment]
Poison pill overload were essential in the Ranges TS to avoid selecting overly general, unconstrained templates like std::swap and std::begin. We don't have that problem with tag_invoke.
