### ISSUE TITLE
Expand the field experience section

### ISSUE THREAD

**Issue by brycelelbach** [brycelelbach/wg21_p2300_std_execution#237]
It should, at a minimum, list:

* libunifex (moral equivalent of ranges-v3/Thrust).
* Reference implementation.
* Michael Costa's Microsoft STL reference implementation.
* Dietmar Kuhl's implementation.
* HPX.

**Comment by miscco** [comment]
Nah, i would not call my ramblings field experience before it has actually done something

**Comment by ericniebler** [comment]
> Nah, i would not call my ramblings field experience before it has actually done something

At the very least, it is a demonstration that it's possible to implement P2300 from the spec, which is not nothing.

**Comment by ericniebler** [comment]
@miscco Am I correct that you are intended to eventually submit your implementation of P2300 upstream to the Microsoft STL?

**Comment by miscco** [comment]
> @miscco Am I correct that you are intended to eventually submit your implementation of P2300 upstream to the Microsoft STL?

Yeah, would not want to waste the effort
