### ISSUE TITLE
specify which implementation-defined types forward which CPOs

### ISSUE THREAD

**Issue by ericniebler** [brycelelbach/wg21_p2300_std_execution#248]
E.g., `then` doesn't say that its sender forwards `get_completion_scheduler`. None of the algorithm-specific receivers are specified to forward any CPOs at all

**Comment by griwes** [comment]
There's blanket wording for this in http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2300r2.html#spec-execution.senders.adaptors.general, paragraphs 4 and 5.

**Comment by ericniebler** [comment]
> all sender adaptors which accept a single sender argument return sender objects that propagate sender queries to that single sender argument

What is a "sender query" and how do you distinguish between a query and an algorithm? Like @lewissbaker says, I don't think we can blindly forward sender queries Luke we do for receiver queries.

**Comment by griwes** [comment]
It's possible that http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2300r2.html#spec-execution.senders.queries needs a sentence that defines "sender query" as any function specified in that section (and probably the same for the equivalent receivers section).

**Comment by ericniebler** [comment]
This is now fixed in the current draft of R4.
