### ISSUE TITLE
Should receiver queries apply to more than just receivers?

### ISSUE THREAD

**Issue by ericniebler** [brycelelbach/wg21_p2300_std_execution#271]
Currently `get_stop_token` and friends are constrained to only work on receivers. In libunifex, we also use them with coroutine promise types. Consider loosening the constraints.

**Comment by kirkshoop** [comment]
Yes. There is more detail in #280, but I expect get_scheduler/get_allocator/get_stop_token and many others to be available from more than just receivers. One of many is that an execution_policy should be able to provide all those things to the existing parallel algos.

**Comment by ericniebler** [comment]
This is already fixed in the current draft of R4.
