### ISSUE TITLE
Wording: text on `schedule_from` invokes `transfer` instead of `schedule_from`

### ISSUE THREAD

**Issue by lucteo** [brycelelbach/wg21_p2300_std_execution#298]
In P2300R3, section 9.6.5.5., at the bottom states:

> Senders returned from `execution::transfer` shall not propagate the sender queries `get_completion_scheduler<CPO>` to an input sender. They shall return a scheduler equivalent to the sch argument from those queries.

Instead of referring to `execution::transfer`, this should refer to `execution::schedule_from`.
(it appears that this block is a copy-paste from `transfer`)

**Comment by ericniebler** [comment]
Thanks!
