### ISSUE TITLE
Fix incorrect uses of inline namespaces in spec

### ISSUE THREAD

**Issue by ericniebler** [brycelelbach/wg21_p2300_std_execution#364]
```c++
  // [execution.queries], general queries
  inline namespace unspecified {
    struct get_scheduler_t;
    inline constexpr get_scheduler_t get_scheduler{};
    struct get_allocator_t;
    inline constexpr get_allocator_t get_allocator{};
    struct get_stop_token_t;
    inline constexpr get_stop_token_t get_stop_token{};
  }
```

The idea was for `get_scheduler_t` to _not_ have `std::execution` as an associated namespace, since we don't want to end up looking there for `tag_invoke` overloads. However, `inline namespace` doesn't achieve that.

Proposed resolution
===================

Change this to:

```c++
  // [execution.queries], general queries
  namespace <i>general-queries</i> {
    struct get_scheduler_t;
    struct get_allocator_t;
    struct get_stop_token_t;
  }
  using <i>general-queries</i>::get_scheduler_t;
  using <i>general-queries</i>::get_allocator_t;
  using <i>general-queries</i>::get_stop_token_t;

  inline constexpr get_scheduler_t get_scheduler{};
  inline constexpr get_allocator_t get_allocator{};
  inline constexpr get_stop_token_t get_stop_token{};
```

Apply this change everywhere.

**Comment by lucteo** [comment]
@ericniebler : I can work on this, but I propose a 2-phase fix for this issue:
1) make the changes just in .bs spec
2) also make the changes in the code

I think it would make sense to fix 2) only after the unit tests that I have are merged (one PR pending and another set of commits that are not yet up). This way, we also have the change tested.

**Comment by lucteo** [comment]
See PR #377  for the changes in the spec only.

**Comment by lucteo** [comment]
@ericniebler: I'm trying to fix this in the code, and I realize the this introduces a usability problem.

types like `set_value_t` are not directly visible by the user. The best thing that the user can do is use `decltype(set_value)` instead. But, this resolves into `const hidden_namespace::set_value_t`.

While I was trying to make the code work by taking the decayed type, this will not work, as we are violating the specification. For example, take the following code:
```
    friend inline_scheduler tag_invoke(
        ex::get_completion_scheduler_t<decltype(ex::set_value)>, my_sender) {
      return {};
    }
```

This will be incompatible with [10.8.3.2](https://brycelelbach.github.io/wg21_p2300_std_execution/std_execution.html#spec-execution.senders.queries.get_completion_scheduler), as the CPO passed to `get_completion_scheduler` needs to be exactly `set_value_t`. A `const set_value_t` is illegal.

Thus, that function should become:
```
    friend inline_scheduler tag_invoke(
        std::decay_t<decltype(ex::get_completion_scheduler)><std::decay_t<decltype(ex::set_value)> >, my_sender) {
      return {};
    }
```

Similarly a completion signature will look like:
```
  struct my_sender : ex::completion_signatures<     //
                         std::decay_t<decltype(ex::set_value)>(), //
                         std::decay_t<decltype(ex::set_error)>(std::exception_ptr)> {
```

As you can see, without type aliases, the user code becomes quite messy.

Please see #392  for how this looks like.

I would propose to also add a note to the specification indicating that the user should use decay_t<decltype(CPO)> (wording change, not semantic change)
