### ISSUE TITLE
Fix section names

### ISSUE THREAD

**Issue by ericniebler** [brycelelbach/wg21_p2300_std_execution#367]
- The section labels are way too long.
As a starter, "execution" should be abbreviated
"exec", "senders.adaptors" should be "adapt"
(there no other kinds of adaptors), and
"senders.consumers" should be just "consumers"
("cons" conflicts with "constructor").

"snd_rec_utils" maybe can be just "utils".

Section labels should not contain underscores;
they look ugly in the font.

**Comment by lucteo** [comment]
see PR #375
