### ISSUE TITLE
{#design-fork}: Clarify different flavours of multi-shot senders

### ISSUE THREAD

**Issue by lewissbaker** [brycelelbach/wg21_p2300_std_execution#39]
The phrasing of section 4.6 seems to imply that all multi-shot senders have the forking semantics. i.e. that you can connect them multiple times to have multiple receivers receive the same result.

However, there are multiple possibilities here which I think should be called out explicitly.
Many of the purely-lazy senders will support being multi-shot-connectable but doing so will result in the sender having multiple independent copies of that operation launched, each potentially starting from scratch.

For example, the `retry_when()` algorithm in libunifex relies on this semantic to be able to retry a given input operation many times if it fails.

However, for an eagerly running operation, the natural thing for supporting multi-shot connect is to have the operation only execute once (it's already running and there is no easy way to start the computation again) and have multiple receivers each receive the same result from that single operation.

I think this section should call out these different interpretations for multi-connect senders explicitly and not leave the reader under the assumption that this always means "forking" a computation - it might mean duplicating a computation.

**Comment by brycelelbach** [comment]
@griwes thinks this may have been addressed by the rewrite that @lewissbaker did in R0 and promises to review it and determine if that is the case tomorrow.

**Comment by griwes** [comment]
I believe that this has indeed been addressed by Lewis' change that landed in R0.
