### ISSUE TITLE
Completion scheduler of `split` and `ensure_started`

### ISSUE THREAD

**Issue by msimberg** [brycelelbach/wg21_p2300_std_execution#420]
10.8.5.1.4 has the catch-all `Unless otherwise specified, all sender adaptors that accept a single sender argument return sender objects that propagate forwarding sender queries to that single sender argument.`, and `split` and `ensure_started` do not specify otherwise, indicating that the `get_completion_scheduler` query should be forwarded (given that #419 is valid...).

The way `split` and `ensure_started` are currently specified means that the completion scheduler is not guaranteed to be the same as that of the input sender `s`. The following says that one of the completion signals may be called in whatever context `start` is called on the operation state returned from connecting `s2` (the sender returned from `split`/`ensure_started`) and `out_r`.

> 5. When execution::start(op_state) is called:
> 
>     If r's receiver contract has already been satisfied, then let Signal be whichever receiver completion-signal was used to complete r’s receiver contract ([exec.recv]). Calls Signal(out_r', args2...), where args2... is a pack of lvalues referencing the subobjects of sh_state that have been saved by the original call to Signal(r, args...) and returns.

The specification should probably either:
- Not forward `get_completion_scheduler` for `split` and `ensure_started`, or
- Make sure `schedule(get_completion_scheduler(s))` is used in an appropriate place inside `split` and `ensure_started`.

**Comment by ericniebler** [comment]
`get_completion_scheduler` is not a forwarding scheduler query, so `split` and `ensure_started` do not have completion schedulers. I don't think there's a problem here. Please reopen if you disagree.
