### ISSUE TITLE
get_completion_signatures doesn't specify how the S::completion_signatures value is constructed

### ISSUE THREAD

**Issue by anthonywilliams** [brycelelbach/wg21_p2300_std_execution#434]
In 10.8.1.1 paragraph 4.2, P2300 says:

> Otherwise, if `remove_cvref_t<S>::completion_signatures` is well-formed and names a type, then a prvalue of `remove_cvref_t<S>::completion_signatures`

However, it doesn't specify how that prvalue is constructed. Presumably it should say something like:

> Otherwise, if `remove_cvref_t<S>::completion_signatures` is well-formed and names a type, then a prvalue of `remove_cvref_t<S>::completion_signatures` **constructed as `remove_cvref_t<S>::completion_signatures{}`**

or something similar.

**Comment by ericniebler** [comment]
Whoops, good point.

**Comment by ericniebler** [comment]
Fixed in `main`.
