### ISSUE TITLE
get_completion_signatures doesn't actually perform tag_invoke

### ISSUE THREAD

**Issue by anthonywilliams** [brycelelbach/wg21_p2300_std_execution#435]
In 10.8.1.1 paragraph 4.1, P2300 says:

>    `tag_invoke_result_t<get_completion_signatures_t, S, E>{}` if that expression is well-formed,

This doesn't actually do the `tag_invoke`, it just constructs an instance of the result type. This seems at odds to every other use of `tag_invoke`. Surely it should just do `return tag_invoke(get_completion_signatures_t{},std::forward<S>(s),std::forward<E>(e));`?

**Comment by ericniebler** [comment]
This is actually intentional. Calling the function would force it to be defined. There's no need to define customizations of `get_completion_signatures`, only its return type matters. You'll notice in the reference implementation, these `tag_invoke` overloads are merely declared, not defined.

**Comment by anthonywilliams** [comment]
Is `tag_invoke` really the right mechanism then? The types are purely empty holder types anyway.

Why not say that the function call operator for `get_completion_signatures` is just declared, not defined, rather than specifying how it constructs the return value?
