### ISSUE TITLE
`sender_of`'s execution environment parameter doesn't work as written and should be removed

### ISSUE THREAD

**Issue by brycelelbach** [brycelelbach/wg21_p2300_std_execution#486]
I think the introduction of the notion of an execution environment for senders has inadvertently made the `sender_of` concept far less user friendly:

Before it was:

```
  template<class S, class... Ts>
    concept sender_of = see below;
```

Now it is:

```
  template<class S, class E = no_env, class... Ts>
    concept sender_of = see below;
```

The default doesn't seem correct - as written, the default will always be used, and any argument you pass after the second will be a part of Ts.

If we removed the default, then the interface would be worse:

Before:

```
sender_of<std::size_t> auto async_read(
    sender_of<std::span<std::byte>> auto buffer,
    auto handle);
```

After:

```
sender_of<std::size_t, no_env> auto async_read(
    sender_of<std::span<std::byte>, no_env> auto buffer,
    auto handle);
```

Given that one of the main reasons we added sender_of was because I wanted it for these examples, I'd rather not make them more complicated. 

I suggest we just hard wire `sender_of` to always use `no_env.

**Comment by ericniebler** [comment]
How do you feel about:

```c++
sender_of< S, set_value_t(Values...), [env]? >
```

... where the trailing `env` is optional and defaults to `no_env`?

Or even:

```c++
using completions_t = completion_signatures< all-signatures...>;
sender_of< S, completions_t, [env]? >
```

**Comment by brycelelbach** [comment]
That seems fine to me.

**Comment by ericniebler** [comment]
Which one? I'm leaning toward the simpler `sender_of< S, set_value_t(Vals...) >` rather than the `completion_signature` one. And maybe limit it to just `set_value_t` so it has the exact same semantics as the current `sender_of` concept.

**Comment by brycelelbach** [comment]
Both seem fine. I'm okay with the environment being a final, default parameter. I don't think I have a strong opinion on the difference between those two options.
