### ISSUE TITLE
Question about chain of async stream in structured concurrency

### ISSUE THREAD

**Issue by npuichigo** [brycelelbach/wg21_p2300_std_execution#509]
Since libunifex have additional concepts of stream or async generator, first I would like to ask whether P2300 will have further extension proposals to support that.

Then, even in current libunifex implementation, I have no idea how to express the concept of chain of async streams. In libunifex, it seems that all the stream functions are sync like `then` here, but I would like a `let_value` version. For example, I have stream B depends on stream A and would like chain with buffer support, much like channels in go (A -> chan -> B)

Stream A and B may have different processing speed and execute on different thread. A channel buffer is necessary, since each time A invokes set_value, B may still be processing previous value and have to resource to handle the new value. In other word, A will invoke set_value to push output values to the buffer and go to the next async iteration, while B only consumes items if needed.

I tried to address this issue with async_scope first, namely spawn a new async scope once one iteration of A is done. However, there’re cases where iterations in B have dependency, and should always be in one async scope. For example, some async operation may be called one once before finished (grpc’s AyncWriter::Write). So I could not spawn multiple async scopes and submit multiple async operations (maybe with co_await)

**Comment by npuichigo** [comment]
@ericniebler @kirkshoop

**Comment by npuichigo** [comment]
Background info in libunifex (https://github.com/facebookexperimental/libunifex/issues/426)

**Comment by npuichigo** [comment]
Here's another real example which is more detailed and it's based on asio and coroutine. Since p2300 is an alternative to asio, I'm seeking for a solution in p2300 or future stream algorithms. (https://github.com/Tradias/asio-grpc/blob/master/example/streaming-server.cpp#L206)

**Comment by kirkshoop** [comment]
Since a sender and an awaitable are interchangeable the Channel could be implemented using sender/receiver instead of coroutines. We have not implemented Channel using sender/receiver yet.

Channel is making design decisions that have too much overhead (buffering) for some use cases. It also is not a basis concept for streaming. In a streaming library, Channel would be an algorithm in some cases and a Subject in others. 

I have a design for a sequence_sender concept in progress. The only new cpo is sequence_connect(), the rest of the cpo's are used for their existing purpose.

**Comment by npuichigo** [comment]
Thx. Channel may have issue if producer and consumer work in different speed. I mentioned Channel here since I did not find a suitable stream algorithm in Rx.

Many stream algorithms are just like a stream-version `then` algorithm. Maybe there will be some stream-version `let_*` algorithms to let an async operation triggers another, but sometimes the trigger logic may be complex.

The trigger logic of async operations in stream often looks like:

<img src="https://user-images.githubusercontent.com/11533479/176819598-2055c3e1-f9a0-4310-9654-e6c0252be26c.png" width=50% height=50%>

1. one stream (often the source stream) is acted like mainline and other `invocable` or async operations are triggered alongwith it.
2. several streams are interleaved to trigger each other.

But if we want to add some degree of parallelization, the dependency is much more complex
<img src="https://user-images.githubusercontent.com/11533479/176819574-9e64cbd9-f106-46ee-a8a9-9e5fb07a2cf4.png" width=75% height=75%>

In this case, to make the most of computation resources, it's better the operations in `when_all` cost same time. If sequence `A` computes much faster, it's best to trigger multiple computation with one IO:
<img src="https://user-images.githubusercontent.com/11533479/176820147-799d6ca2-9db1-4b7a-8c7a-6d279c605c91.png" width=75% height=75%>

Compared with Channel with may have overhead, these algorithms are more complicated. Or maybe there's something wrong with me. Hope you can give me some insights.

BTW, is `sequence_sender` available now somewhere to have a peek?

**Comment by kirkshoop** [comment]
If the order of the writes does not matter, then a strand scheduler is sufficient.
If the data read needs multiple consumers or the writes need to be ordered, then a buffer is a solution for both requirements.

```
async_scope scope;
async_buffer buffer;

when_all(
  repeat(
    // producer
    let_value(read(), [](auto v) {
      // post only completes when the 
      // data is placed in the buffer.
      // this is back-pressure
      return buffer.post(v);
    })),
  // consumer (writer)
  repeat(
    let_value(buffer.get(), [](auto v){
      return write(v);
    })),
  //  consumer (serial-processor)
  repeat(
    let_value(buffer.get(), [](auto v){
      return process(v);
    })),
  //  consumer (parallel-processor)
  when_all(
    repeat(
      then(buffer.get(), [](auto v){
        scope.spawn(process(v));
      })),
    scope.complete()));
```

---

'select as in rust/golang' is not the part that concerns me.
what does `A || B || C` do with `B` and `C` when `A` completes first?
what does the `alert` do when the deadline is exceeded?

**Comment by npuichigo** [comment]
Thanks. asio just implements

**Comment by npuichigo** [comment]
Thanks. asio just implements `A || B || C` as cancel the others if one is already successful without any error.

https://github.com/chriskohlhoff/asio/blob/5302adea05c8a1c5d3923fa93afd7cf437df5937/asio/include/asio/experimental/awaitable_operators.hpp#L253-L265
