### ISSUE TITLE
What's the difference of __movable_value and movable?

### ISSUE THREAD

**Issue by npuichigo** [brycelelbach/wg21_p2300_std_execution#529]
I can't get the idea of using __movable_value here and what's the difference?
```c++
template < class T >
concept movable =
  std::is_object_v<T> &&
  std::move_constructible<T> &&
  std::assignable_from<T&, T> &&
  std::swappable<T>;

template <class _T>
concept __movable_value =
    move_constructible<decay_t<_T>> && constructible_from<decay_t<_T>, _T>;
```

**Comment by ericniebler** [comment]
`movable` is the full set of operations you would expect a "movable" object type to support. `__movable_value` is more narrowly targeted to the following use case:

```c++
// Move constructible, not copy constructible or assignable:
struct S {
  S() = default;
  S(S&&) = default;
};

static_assert(__movable_value<S>);

template <__movable_value T>
struct box {
  T value_;
};

static_assert(__movable_value<box<S>>);

template <__movable_value T>
box<T> f(T&& t) {
  return {(T&&) t};
}

int main() {
  auto b = f(S{});
}
```

The idea is that if a function template accepts a type by forwarding reference and then returns the object wrapped in a struct (as with `f` and `box<T>`), `__movable_value` is the set of operations needed to do that. Notably, it does not require copyability or move-assignability, but is _does_ require that it can be decay-copied from the function argument.

This is needed by the sender adaptors. Senders must be move-constructible, but not copyable and not move-assignable.

Pls feel free to reopen if this does not answer your question.
