### ISSUE TITLE
server_theme.on_transfer example is randomly crashing

### ISSUE THREAD

**Issue by ericniebler** [brycelelbach/wg21_p2300_std_execution#530]
Repeated runs of the example on a machine with sufficient concurrency occasionally results in:

```bash
example.server_theme.on_transfer: /home/[...]/intrusive_queue.hpp:44: 
example::intrusive_queue<&example::task_base::next>::~intrusive_queue() [Next = &example::task_base::next]:
Assertion `empty()' failed.
```

There is some race condition I haven't been able to track down. It could be a bug in `intrusive_queue`, `static_thread_pool`, or the [example](https://github.com/brycelelbach/wg21_p2300_std_execution/blob/main/examples/server_theme/on_transfer.cpp) itself.

I'm tagging @lucteo and @lewissbaker here, the authors of the questionable bits.

**Comment by lewissbaker** [comment]
It looks like a bug in the example.
It's calling `ex::spawn_detached()` which then means it cannot join the work before destroying the `static_thread_pool`.

The `static_thread_pool` class requires that the caller ensure that all work scheduled to it has completed before you call the destructor of the `static_thread_pool`. This is why you're failing the assert in the `intrusive_queue` destructor, which requires that the queue be empty.

You need to use an `async_scope` (or similar) to ensure spawned work is joined before you call the destructor of the execution context that the work is running on.
