### ISSUE TITLE
Conan packages can no longer be built

### ISSUE THREAD

**Issue by paulbendixen** [brycelelbach/wg21_p2300_std_execution#591]
After moving the reterival of Catch from conan to CPM, the ability to build the library as a package was removed.

The conanfile.py and files in test_package should be restored, this should in no way hinder the usage of CPM

(possibly the generator should be changed to be cmake_find_package)

**Comment by ericniebler** [comment]
We removed conan because it was proving to be an obstacle to adoption. It's too difficult to set up for people who just want to build the code and are familiar already with CMake.

Does this PR require anybody to install conan if all they want to do is build the examples and the tests?

**Comment by paulbendixen** [comment]
No, the point is that this provides an easy way of consuming the package for anyone wanting to use conan, but doesn't require anyone to use conan.
